### ISSUE TITLE
Setup testnet state of burning token scenario

### ISSUE THREAD

**Issue by justinbarry** [onflow/flow-multisig#13]
Reproducible scripts to set up "authorized" accounts (take from flowscan) states to mimic production accounts that need to free frozen tokens.

 ### To deliver
 * Cadence creation scripts to create multisig accounts with tokens balance.  

This is need to test burning tokens process and UX.

Todo: 

flowscan script that was used to create one of the authorized multisig accounts.

https://flowscan.org/transaction/6efa6a16e9c3e66d33bd1ba593a386383e72ca4c80d042caa1bb750832202756/script

Look in flow core contracts, to get testnet contract addresses: 
1. FungibleToken
2. FlowToken

figure out arguments.json 
 * on mainnet the contract takes in these args:
```
 partialAdminPublicKey: [UInt8], // Weight: 100
 partialUserPublicKey: [UInt8], // Weight: 900
```
 * use this to decode String to [Uint8]
```
publicKey: publicKey.decodeHex(),
```
 * new script will look like this:
```
 partialAdminPublicKey: String, // Weight: 100
 partialUserPublicKey: String, // Weight: 900
```
example of arg:
`[{"type":"String","value":"39863a608f3356590a3800ad978778649d0a981f59cf993dc4f8966942c36cda5b2fda128a9fd3bf00a78cf31cadf4a8e946c8d46f272226ae4aa64c90961508"}]`

testnet states to create
1. Cli-Blockto-testnet setup
2. Cli-Ledger testnet setup

**Comment by bthaile** [comment]
flowscan script that was used to create one of the authorized multisig accounts.

https://flowscan.org/transaction/6efa6a16e9c3e66d33bd1ba593a386383e72ca4c80d042caa1bb750832202756/script

**Comment by justinbarry** [comment]
@bthaile You finished this, yeah?

**Comment by bthaile** [comment]
CLI-Ledger testnet scripts to create state task is done.

Working on other testnet scripts to create state for:
 - CLI-blocto (non-custodial) 
 - Fe-ona (sp?) so they can test, they need to originate the transaction.

**Comment by bthaile** [comment]
Done, scripts have been checked in to support creating testnet and mainnet state for testing.
